In [2]:
import scipy as sp
import pandas
import numpy as np

In [27]:
baggage_type = [40,50,60,70]
hours_rented = [1,2,3,4]
hours_finally_rented = [1+1,2,3,4+1]

matrix = np.array([baggage_type,hours_rented,hours_finally_rented])
print(matrix)


available_space_values = [5,10,15,20]
available_space = np.random.choice(available_space_values, 20)
print(available_space)

[[40 50 60 70]
 [ 1  2  3  4]
 [ 2  2  3  5]]
[20 10 10  5 15 10 15  5  5 15 20 15 15 10 10 15 20 20 15 10]
